export interface TokenCategory {
    [token: string]: string;
}
export interface ThemeTokens {
    'color-background': TokenCategory;
    'color-text': TokenCategory;
    'color-border': TokenCategory;
    'color-shape': TokenCategory;
    'spacing': TokenCategory;
    'text-size': TokenCategory;
    'radius': TokenCategory;
}
export interface PrimitiveTokens {
    'other': TokenCategory;
}
export declare enum ColorBackgroundTokens {
    InputDefault = "--token-color-background-input-default",
    InputDisabled = "--token-color-background-input-disabled",
    InputSelected = "--token-color-background-input-selected",
    InteractiveAlertActive = "--token-color-background-interactive-alert-active",
    InteractiveAlertDefault = "--token-color-background-interactive-alert-default",
    InteractiveAlertHover = "--token-color-background-interactive-alert-hover",
    InteractiveDisabled = "--token-color-background-interactive-disabled",
    InteractiveNeutralActive = "--token-color-background-interactive-neutral-active",
    InteractiveNeutralAlertActive = "--token-color-background-interactive-neutral-alert-active",
    InteractiveNeutralAlertHover = "--token-color-background-interactive-neutral-alert-hover",
    InteractiveNeutralDefault = "--token-color-background-interactive-neutral-default",
    InteractiveNeutralHover = "--token-color-background-interactive-neutral-hover",
    InteractiveNeutralSelected = "--token-color-background-interactive-neutral-selected",
    InteractivePrimaryActive = "--token-color-background-interactive-primary-active",
    InteractivePrimaryDefault = "--token-color-background-interactive-primary-default",
    InteractivePrimaryHover = "--token-color-background-interactive-primary-hover",
    StatusAlert = "--token-color-background-status-alert",
    StatusInprogress = "--token-color-background-status-inprogress",
    StatusNeutral = "--token-color-background-status-neutral",
    StatusQueue = "--token-color-background-status-queue",
    StatusSuccess = "--token-color-background-status-success",
    StatusWarning = "--token-color-background-status-warning",
    SurfaceAlert = "--token-color-background-surface-alert",
    SurfaceDisabled = "--token-color-background-surface-disabled",
    SurfaceInprogress = "--token-color-background-surface-inprogress",
    SurfacePrimary = "--token-color-background-surface-primary",
    SurfaceScrimmed = "--token-color-background-surface-scrimmed",
    SurfaceSecondary = "--token-color-background-surface-secondary",
    SurfaceSuccess = "--token-color-background-surface-success",
    SurfaceTertiary = "--token-color-background-surface-tertiary",
    SurfaceTooltipNeutral = "--token-color-background-surface-tooltip-neutral",
    SurfaceTooltipPrimary = "--token-color-background-surface-tooltip-primary",
    SurfaceWarning = "--token-color-background-surface-warning"
}
export declare enum ColorTextTokens {
    AccentBambooSoft = "--token-color-text-accent-bamboo-soft",
    AccentBambooStrong = "--token-color-text-accent-bamboo-strong",
    AccentCharchoalSoft = "--token-color-text-accent-charchoal-soft",
    AccentCharchoalStrong = "--token-color-text-accent-charchoal-strong",
    AccentCyanSoft = "--token-color-text-accent-cyan-soft",
    AccentCyanStrong = "--token-color-text-accent-cyan-strong",
    AccentGrassSoft = "--token-color-text-accent-grass-soft",
    AccentGrassStrong = "--token-color-text-accent-grass-strong",
    AccentGraySoft = "--token-color-text-accent-gray-soft",
    AccentGrayStrong = "--token-color-text-accent-gray-strong",
    AccentGreenSoft = "--token-color-text-accent-green-soft",
    AccentGreenStrong = "--token-color-text-accent-green-strong",
    AccentLemonSoft = "--token-color-text-accent-lemon-soft",
    AccentLemonStrong = "--token-color-text-accent-lemon-strong",
    AccentLimeSoft = "--token-color-text-accent-lime-soft",
    AccentLimeStrong = "--token-color-text-accent-lime-strong",
    AccentMagentaSoft = "--token-color-text-accent-magenta-soft",
    AccentMagentaStrong = "--token-color-text-accent-magenta-strong",
    AccentOrangeSoft = "--token-color-text-accent-orange-soft",
    AccentOrangeStrong = "--token-color-text-accent-orange-strong",
    AccentPeacockSoft = "--token-color-text-accent-peacock-soft",
    AccentPeacockStrong = "--token-color-text-accent-peacock-strong",
    AccentPurpleSoft = "--token-color-text-accent-purple-soft",
    AccentPurpleStrong = "--token-color-text-accent-purple-strong",
    AccentSeaSoft = "--token-color-text-accent-sea-soft",
    AccentSeaStrong = "--token-color-text-accent-sea-strong",
    AccentSkySoft = "--token-color-text-accent-sky-soft",
    AccentSkyStrong = "--token-color-text-accent-sky-strong",
    AccentSunSoft = "--token-color-text-accent-sun-soft",
    AccentSunStrong = "--token-color-text-accent-sun-strong",
    AccentWoodSoft = "--token-color-text-accent-wood-soft",
    AccentWoodStrong = "--token-color-text-accent-wood-strong",
    AccentYellowSoft = "--token-color-text-accent-yellow-soft",
    AccentYellowStrong = "--token-color-text-accent-yellow-strong",
    BodyAlert = "--token-color-text-body-alert",
    BodyDisabled = "--token-color-text-body-disabled",
    BodyInverse = "--token-color-text-body-inverse",
    BodyPlaceholder = "--token-color-text-body-placeholder",
    BodyPrimary = "--token-color-text-body-primary",
    BodySecondary = "--token-color-text-body-secondary",
    BodySuccess = "--token-color-text-body-success",
    BodyWarning = "--token-color-text-body-warning",
    InteractiveAlertActive = "--token-color-text-interactive-alert-active",
    InteractiveAlertDefault = "--token-color-text-interactive-alert-default",
    InteractiveAlertHover = "--token-color-text-interactive-alert-hover",
    InteractiveDisabled = "--token-color-text-interactive-disabled",
    InteractiveHeavy = "--token-color-text-interactive-heavy",
    InteractiveInverse = "--token-color-text-interactive-inverse",
    InteractivePrimaryActive = "--token-color-text-interactive-primary-active",
    InteractivePrimaryDefault = "--token-color-text-interactive-primary-default",
    InteractivePrimaryHover = "--token-color-text-interactive-primary-hover"
}
export declare enum ColorBorderTokens {
    DividerDefault = "--token-color-border-divider-default",
    InteractiveAlertDefault = "--token-color-border-interactive-alert-default",
    InteractiveAlertFocused = "--token-color-border-interactive-alert-focused",
    InteractiveAlertHover = "--token-color-border-interactive-alert-hover",
    InteractiveDefault = "--token-color-border-interactive-default",
    InteractiveDisabled = "--token-color-border-interactive-disabled",
    InteractiveFocused = "--token-color-border-interactive-focused",
    InteractiveHover = "--token-color-border-interactive-hover",
    InteractiveInverse = "--token-color-border-interactive-inverse",
    InteractivePrimaryDefault = "--token-color-border-interactive-primary-default",
    InteractivePrimaryFocused = "--token-color-border-interactive-primary-focused",
    InteractivePrimaryHover = "--token-color-border-interactive-primary-hover",
    InteractiveSelected = "--token-color-border-interactive-selected",
    SurfaceAlert = "--token-color-border-surface-alert",
    SurfaceDefault = "--token-color-border-surface-default",
    SurfaceInfo = "--token-color-border-surface-info",
    SurfaceSuccess = "--token-color-border-surface-success",
    SurfaceWarning = "--token-color-border-surface-warning"
}
export declare enum ColorShapeTokens {
    AccentBambooPale = "--token-color-shape-accent-bamboo-pale",
    AccentBambooSoft = "--token-color-shape-accent-bamboo-soft",
    AccentBambooStrong = "--token-color-shape-accent-bamboo-strong",
    AccentCharcoalPale = "--token-color-shape-accent-charcoal-pale",
    AccentCharcoalSoft = "--token-color-shape-accent-charcoal-soft",
    AccentCharcoalStrong = "--token-color-shape-accent-charcoal-strong",
    AccentCyanPale = "--token-color-shape-accent-cyan-pale",
    AccentCyanSoft = "--token-color-shape-accent-cyan-soft",
    AccentCyanStrong = "--token-color-shape-accent-cyan-strong",
    AccentGrassPale = "--token-color-shape-accent-grass-pale",
    AccentGrassSoft = "--token-color-shape-accent-grass-soft",
    AccentGrassStrong = "--token-color-shape-accent-grass-strong",
    AccentGrayPale = "--token-color-shape-accent-gray-pale",
    AccentGraySoft = "--token-color-shape-accent-gray-soft",
    AccentGrayStrong = "--token-color-shape-accent-gray-strong",
    AccentGreenPale = "--token-color-shape-accent-green-pale",
    AccentGreenSoft = "--token-color-shape-accent-green-soft",
    AccentGreenStrong = "--token-color-shape-accent-green-strong",
    AccentLemonPale = "--token-color-shape-accent-lemon-pale",
    AccentLemonSoft = "--token-color-shape-accent-lemon-soft",
    AccentLemonStrong = "--token-color-shape-accent-lemon-strong",
    AccentLimePale = "--token-color-shape-accent-lime-pale",
    AccentLimeSoft = "--token-color-shape-accent-lime-soft",
    AccentLimeStrong = "--token-color-shape-accent-lime-strong",
    AccentMagentaPale = "--token-color-shape-accent-magenta-pale",
    AccentMagentaSoft = "--token-color-shape-accent-magenta-soft",
    AccentMagentaStrong = "--token-color-shape-accent-magenta-strong",
    AccentOrangePale = "--token-color-shape-accent-orange-pale",
    AccentOrangeSoft = "--token-color-shape-accent-orange-soft",
    AccentOrangeStrong = "--token-color-shape-accent-orange-strong",
    AccentPeacockPale = "--token-color-shape-accent-peacock-pale",
    AccentPeacockSoft = "--token-color-shape-accent-peacock-soft",
    AccentPeacockStrong = "--token-color-shape-accent-peacock-strong",
    AccentPurplePale = "--token-color-shape-accent-purple-pale",
    AccentPurpleSoft = "--token-color-shape-accent-purple-soft",
    AccentPurpleStrong = "--token-color-shape-accent-purple-strong",
    AccentSeaPale = "--token-color-shape-accent-sea-pale",
    AccentSeaSoft = "--token-color-shape-accent-sea-soft",
    AccentSeaStrong = "--token-color-shape-accent-sea-strong",
    AccentSkyPale = "--token-color-shape-accent-sky-pale",
    AccentSkySoft = "--token-color-shape-accent-sky-soft",
    AccentSkyStrong = "--token-color-shape-accent-sky-strong",
    AccentSunPale = "--token-color-shape-accent-sun-pale",
    AccentSunSoft = "--token-color-shape-accent-sun-soft",
    AccentSunStrong = "--token-color-shape-accent-sun-strong",
    AccentWoodPale = "--token-color-shape-accent-wood-pale",
    AccentWoodSoft = "--token-color-shape-accent-wood-soft",
    AccentWoodStrong = "--token-color-shape-accent-wood-strong",
    AccentYellowPale = "--token-color-shape-accent-yellow-pale",
    AccentYellowSoft = "--token-color-shape-accent-yellow-soft",
    AccentYellowStrong = "--token-color-shape-accent-yellow-strong",
    InteractiveAlertActive = "--token-color-shape-interactive-alert-active",
    InteractiveAlertDefault = "--token-color-shape-interactive-alert-default",
    InteractiveAlertHover = "--token-color-shape-interactive-alert-hover",
    InteractiveDisabled = "--token-color-shape-interactive-disabled",
    InteractiveHeavy = "--token-color-shape-interactive-heavy",
    InteractiveInverse = "--token-color-shape-interactive-inverse",
    InteractiveNeutralDefault = "--token-color-shape-interactive-neutral-default",
    InteractiveNeutralDisabled = "--token-color-shape-interactive-neutral-disabled",
    InteractiveNeutralHover = "--token-color-shape-interactive-neutral-hover",
    InteractivePrimaryActive = "--token-color-shape-interactive-primary-active",
    InteractivePrimaryDefault = "--token-color-shape-interactive-primary-default",
    InteractivePrimaryHover = "--token-color-shape-interactive-primary-hover",
    InteractivePrimarySelected = "--token-color-shape-interactive-primary-selected",
    Light = "--token-color-shape-light",
    Primary = "--token-color-shape-primary",
    StatusAlert = "--token-color-shape-status-alert",
    StatusInfo = "--token-color-shape-status-info",
    StatusSuccess = "--token-color-shape-status-success",
    StatusWarning = "--token-color-shape-status-warning"
}
export declare enum SpacingTokens {
    Lg = "--token-spacing-lg",
    Md = "--token-spacing-md",
    Sm = "--token-spacing-sm",
    Xl = "--token-spacing-xl",
    Xs = "--token-spacing-xs",
    Xxl = "--token-spacing-xxl",
    Xxs = "--token-spacing-xxs",
    Xxxl = "--token-spacing-xxxl",
    Xxxs = "--token-spacing-xxxs"
}
export declare enum TextSizeTokens {
    Lg = "--token-text-size-lg",
    Md = "--token-text-size-md",
    Sm = "--token-text-size-sm",
    Xl = "--token-text-size-xl",
    Xs = "--token-text-size-xs",
    Xxl = "--token-text-size-xxl",
    Xxxl = "--token-text-size-xxxl"
}
export declare enum RadiusTokens {
    Lg = "--token-radius-lg",
    Max = "--token-radius-max",
    Md = "--token-radius-md",
    Sm = "--token-radius-sm",
    Xs = "--token-radius-xs"
}
export interface Tokens {
    'Green Mode': ThemeTokens;
    'Blue Mode': ThemeTokens;
    'Primitives': PrimitiveTokens;
}
export declare const tokens: Tokens;
